version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: universal_sompo_rcu_assistant
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/static/uploads:/app/backend/static/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
